#' Sample loss experience data
#'
#' @description
#' Fully synthetic long-format loss experience data for demonstrating
#' the lossratio package workflow. Generated deterministically from
#' `data-raw/make_experience.R` (set.seed = 20260501); not derived from
#' any real portfolio. Categorical structure (4 coverages, 9 age bands,
#' 2 genders, 30 cohort months) and broad loss-ratio magnitudes are
#' chosen to make the package examples behave plausibly, but row-level
#' values carry no real-world signal.
#'
#' @format A `data.table` with 33,480 rows and 17 columns:
#' \describe{
#'   \item{cy, cyh, cyq, cym}{Calendar period (year / half / quarter / month) as `Date`.}
#'   \item{uy, uyh, uyq, uym}{Underwriting period (year / half / quarter / month) as `Date`.}
#'   \item{elap_y, elap_h, elap_q, elap_m}{Elapsed period (year / half / quarter / month) as integer.}
#'   \item{cv_nm}{Coverage name (character).}
#'   \item{age_band}{Age band (ordered factor).}
#'   \item{gender}{Gender (factor).}
#'   \item{loss}{Loss amount (perturbed).}
#'   \item{rp}{Risk premium amount (perturbed).}
#' }
#'
#' @source Generated by `data-raw/make_experience.R`. Fully synthetic;
#'   no portfolio data dependency.
#'
#' @examples
#' \dontrun{
#' data(experience)
#' head(experience)
#'
#' exp <- as_experience(experience)
#' tri <- build_triangle(exp, group_var = cv_nm)
#' }
"experience"
